# Generated by Django 4.2.23 on 2025-07-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_article_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="location_images/"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
