# Generated by hand to add category field to Location

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_location_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="category",
            field=models.CharField(max_length=50, blank=True, null=True, default="其他"),
        ),
    ]


